### PR TITLE
DRFT-245 Fixes handling of auth_key is None

### PR DESCRIPTION
**Pull request by petrblaho**
## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [x] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [x] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by petrblaho** [comment]
This is fixup of two issues found in handling of variables:
- `auth_key` can be None in some cases
- `audit_message` should be present in the beginning of the method

**Comment by petrblaho** [comment]
https://issues.redhat.com/browse/DRFT-131

**Review by CodeHeeler — APPROVED** [review]
LGTM, thanks!

**Comment by petrblaho** [comment]
Thank you, @CodeHeeler , merging.

**Pull request merged**
