### PR TITLE
Adds OBFUSCATED_FACTS_PATTERNS constant

### PR DESCRIPTION
**Pull request by petrblaho**
This is used in drift-backend to find and mark fact values as obfuscated
/ redacted.

### CODE REVIEW

**Comment by petrblaho** [comment]
https://github.com/RedHatInsights/drift-backend/pull/215

**Comment by petrblaho** [comment]
https://issues.redhat.com/browse/DRFT-30

**Comment by petrblaho** [comment]
@eherget

**Review by eherget — APPROVED** [review]
This looks good and it can be merged once the title of the PR is changed to remove WIP and add in the Jira task/story.  After that Dana or Eric can walk Petr through the process to tag kerlescan and then update the drift-backend dependency on kerlescan to the new tag before merging the drift-backend PR.

**Comment by petrblaho** [comment]
I updated commit message with link to Jira task and removed [wip] from PR name.

**Pull request merged**
